


num_autoregressive_steps: 8





inner_model_cfg:
  img_channels: 3
  num_steps_conditioning: 2
  cond_channels: 256
  depths: [2, 2, 2, 2]
  channels: [64, 64, 64, 64]
  attn_depths: [0, 0, 0, 0]
  num_actions: 2
  num_hidden_layers_action: 0
  action_is_discrete: False

data: 
  dt: "0.1"
  data_ids:
    # - "2024-12-06__16-33-06"
    - "2024-12-06__19-11-22" 
    - "2024-12-08__13-00-39" 
    - "2024-12-06__19-39-10"
    - "2024-12-08__12-33-54"

train:
  batch_size: 8

evaluate_every: 2000
save_every: 2000


wandb:
  enabled: true            # Enable or disable wandb logging
  project: "world_model_diamond"  # Replace with your wandb project name
  name: null               # Run name; if null, wandb generates one